using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class HomeInfoControl : MonoBehaviour
{
    private Text cashTv, fruitNumTv, songProgressTv;
    private Image songProgress;
    private void Awake()
    {
        //cashTv = transform.Find("Top/WithDraw/CashNumTv").transform.GetComponent<Text>();
        //fruitNumTv = transform.Find("Top/ForFruit/FruitNumTv").transform.GetComponent<Text>();
        //songProgressTv = transform.Find("Top/SongProgress/ProgressTv").transform.GetComponent<Text>();
        //songProgress = transform.Find("Top/SongProgress/ProgressBar").transform.GetComponent<Image>();
    }




    // Start is called before the first frame update
    void Start()
    {
#if UNITY_EDITOR
        AppConfig.Instance.InitProgect(true);
#endif
        //GetHomeInfo();
        //获取下一组要生成的水果的音符
        //GameController.GetInstance().GetNextNoteList(0);
        //

        UIMgr.Getinstance().ShowPanel<MainPanel>(E_Layer.mid);
        UIMgr.Getinstance().ShowPanel<TouchPanel>(E_Layer.bot);

        GameController.GetInstance().GetSongsList(0);
        GameController.GetInstance().GetWithdrawList(1);
    }







}
