using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class HomeInfoControl : MonoBehaviour
{
    private Text cashTv, fruitNumTv, songProgressTv;
    private Image songProgress;
    private void Awake()
    {
        //cashTv = transform.Find("Top/WithDraw/CashNumTv").transform.GetComponent<Text>();
        //fruitNumTv = transform.Find("Top/ForFruit/FruitNumTv").transform.GetComponent<Text>();
        //songProgressTv = transform.Find("Top/SongProgress/ProgressTv").transform.GetComponent<Text>();
        //songProgress = transform.Find("Top/SongProgress/ProgressBar").transform.GetComponent<Image>();
    }




    // Start is called before the first frame update
    void Start()
    {
#if UNITY_EDITOR
        AppConfig.Instance.InitProgect(true);
#endif

        EventCenter.Getinstance().EventTrigger("RegisterPanel");

        GameController.GetInstance().GetWithdrawList(1);
        GameController.GetInstance().GetReward();


    }







}
